import { Link, useParams } from 'react-router-dom';
import { getCase, getEvidence, getForensicSummary } from '../api/cases';
import { useApiResource } from '../api/useApiResource';
import type { ForensicSummary } from '../types';

export default function OverviewPage() {
  const { caseId = '' } = useParams(); const c = useApiResource(() => getCase(caseId), caseId); const findings = useApiResource(() => getEvidence(caseId), `e-${caseId}`); const forensic = useApiResource<ForensicSummary>(() => getForensicSummary(caseId), `fs-${caseId}`);
  if (c.loading) return <p>Loading case…</p>; if (c.error || !c.data) return <p className="text-error">{c.error}</p>; const x = c.data;
  return <div className="space-y-6"><header><p className="text-on-surface-variant">Investigation</p><h1 className="font-headline-lg">Case #{x.number}</h1><p>{x.subject}</p><p className="text-on-surface-variant">From {x.senderName} &lt;{x.senderEmail}&gt; · Received {x.receivedDate}</p></header><div className="grid md:grid-cols-4 gap-3">{[['Risk', `${x.riskScore}/100`], ['Identity consistency', `${x.identityConsistency}/100`], ['Analysis confidence', `${x.modelConfidence}%`], ['Evidence confidence', `${x.evidenceConfidence}%`]].map(([k, v]) => <section key={k} className="p-4 rounded-xl bg-surface-container-low"><p>{k}</p><strong className="text-2xl">{v}</strong></section>)}</div><section className="p-4 rounded-xl bg-surface-container-low"><h2>Authentication observations</h2><p>SPF: {x.spfResult} · DKIM: {x.dkimResult} · DMARC: {x.dmarcResult}</p><p className="text-on-surface-variant">Authentication results are evidence about message handling; they do not by themselves establish sender intent.</p></section>{forensic.data?.evidenceId ? <section className="p-4 rounded-xl bg-surface-container-low"><h2>Evidence</h2><p>MIME parts: {forensic.data.mimeParts} · Received hops: {forensic.data.receivedHops} · Attachments: {forensic.data.attachments} · Observables: {forensic.data.iocs}</p><Link className="text-primary" to={`/case/${caseId}/evidence`}>Review evidence →</Link></section> : null}<section><h2>Evidence findings</h2>{findings.loading ? <p>Loading findings…</p> : findings.data?.length ? findings.data.map(f => <article key={f.id} className="p-3 my-2 bg-surface-container-low rounded-xl"><strong>{f.title}</strong><p>{f.description}</p><small>{f.evidenceState} · {f.confidence}% · {f.source}</small></article>) : <p>No derived findings are available.</p>}<Link className="text-primary" to={`/case/${caseId}/evidence`}>Review all evidence →</Link></section></div>;
}
